# Generated by Django 4.2.5 on 2023-10-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="token",
            field=models.CharField(
                default=2, max_length=64, unique=True, verbose_name="Токен"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="todo",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
