# Generated by Django 4.2.5 on 2023-10-23 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0002_todo_token_alter_todo_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="is_complete",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="token",
        ),
    ]
