# Generated by Django 4.2.5 on 2023-10-24 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0003_remove_todo_is_complete_remove_todo_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "uuid",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "task_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="todolist.todo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "task_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="todolist.todo"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="todolist.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttachedFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=255)),
                (
                    "loader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="todolist.user"
                    ),
                ),
                (
                    "task_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="todolist.todo"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="todo",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="todolist.user",
            ),
        ),
    ]
