# Generated by Django 4.2.5 on 2023-10-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0004_user_project_attachedfile_todo_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="is_complete",
            field=models.BooleanField(default=False, verbose_name="Завершено"),
        ),
    ]
