# Generated by Django 4.2.5 on 2023-10-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0005_todo_is_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachedfile",
            name="file",
            field=models.FileField(null=True, upload_to="attached_files/"),
        ),
    ]
