# Generated by Django 4.2.5 on 2023-10-25 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0006_attachedfile_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachedfile",
            name="loader",
        ),
        migrations.RemoveField(
            model_name="attachedfile",
            name="type",
        ),
    ]
