# Generated by Django 4.2.5 on 2023-10-25 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0007_remove_attachedfile_loader_remove_attachedfile_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attachedfile",
            old_name="task_id",
            new_name="task",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="task_id",
            new_name="task",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="todo",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="task_id",
        ),
        migrations.AddField(
            model_name="user",
            name="assigned_tasks",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_to_user",
                to="todolist.todo",
            ),
        ),
    ]
