# Generated by Django 4.2.5 on 2023-10-30 07:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0008_rename_task_id_attachedfile_task_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="user",
        ),
    ]
