# Generated by Django 4.2.5 on 2023-10-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0009_remove_project_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="user",
        ),
        migrations.AddField(
            model_name="project",
            name="title",
            field=models.CharField(
                default="Project", max_length=255, verbose_name="Название проекта"
            ),
        ),
    ]
