# Generated by Django 4.2.5 on 2023-11-06 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0012_user_todo_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
