# Generated by Django 4.2.5 on 2023-11-06 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0017_alter_todo_username"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
